import ScrollProgress from "../../components/ScrollProgress";
import ScrollReveal from "../../components/ScrollReveal";
import FlagshipSchool from "../../components/programmes/FlagshipSchool";
import ProgrammeFeature from "../../components/programmes/ProgrammeFeature";
import ProgrammesHero from "../../components/programmes/ProgrammesHero";
import { CompletedPilot, ProgrammesCta } from "../../components/programmes/ProgrammesFooterSections";

export const metadata = { title: "Programmes | AIM Foundation", description: "AIM Foundation builds healthcare innovation for India's public health system through its flagship Amaravati School of Biodesign, with programmes including Janani Mitra delivered with State Governments in Andhra Pradesh and Telangana." };

const programmes = [
  { id: "janani-mitra", number: "01", name: "Janani Mitra", strapline: "AI-Enabled Maternal Nutrition", tags: ["SDG 2 · Zero Hunger", "SDG 3 · Good Health and Well-being", "SDG 5 · Gender Equality", "SDG 17 · Partnerships for the Goals"], details: [["What It Is", "A digital maternal nutrition programme built on the MDD-W dietary diversity method, delivered through ASHA workers, ANMs and Medical Officers using the existing public health system."], ["Where It Is", "Andhra Pradesh and Telangana, in partnership with the State Governments."], ["Partners", "Government of Andhra Pradesh, Government of Telangana, AIG Hospitals, Forsys Inc."], ["Clinical Validation", "Programme model vetted by AIG Hospitals clinicians. Nutritional guidance validated by the Head of the Department of Clinical Nutrition and Dietetics, AIG Hospitals."], ["Reach And Cost", "Designed to reach 1,00,000 women at ₹100 per beneficiary."], ["How To Support", "At ₹100 per beneficiary, support is measured directly in women reached. Corporate and foundation partners receive programme-wise budgets, milestone-linked disbursement and regular progress reporting."]] },
  { id: "gut-microbiome-study", number: "02", name: "Gut Microbiome Study", strapline: "Population Health Research", tags: ["SDG 3 · Good Health and Well-being", "SDG 17 · Partnerships for the Goals"], details: [["What It Is", "A population-scale study of the gut microbiome in rural Andhra Pradesh, generating reference data currently absent for Indian populations."], ["Where It Is", "Recruitment across the Primary Health Centre network in Andhra Pradesh."], ["Cohort", "The study is designed for 90,000 participants."], ["Partners", "AIG Hospitals (laboratory processing, sequencing, bioinformatics and scientific leadership from the Barry Marshall Laboratory), Government of Andhra Pradesh (Primary Health Centre network access, ASHA and ANM mobilisation)."], ["Ethics And Data", "Ethics approval received from the AIG Hospitals Institutional Ethics Committee. Study data is owned by AIM Foundation."], ["How To Support", "Support funds participant recruitment, sample collection and sequencing capacity across the 90,000-participant cohort. Research partners and funders receive joint outcome frameworks and co-branded reporting."]] },
];

export default function ProgrammesPage() {
  return <main className="bg-[#fbfafc]"><ScrollProgress /><ProgrammesHero /><FlagshipSchool /><section className="bg-[#fbfafc] pb-5 pt-[83px] md:pb-[35px] md:pt-[140px]" aria-labelledby="programmes-list-heading"><div className="mx-auto w-[calc(100%-48px)] max-w-[1304px] md:w-[min(100%-96px,1304px)]"><ScrollReveal><p className="eyebrow eyebrow--dark !text-[16px] md:!text-[18px]"><span /> Built Under The School</p><h2 className="mt-[18px] text-[47px] font-medium leading-[.93] tracking-[-.073em] md:whitespace-nowrap md:text-[clamp(47px,5.4vw,78px)]" id="programmes-list-heading">Programmes Delivered <span className="font-[family-name:var(--font-playfair)] font-medium tracking-[-.075em] not-italic">With Governments</span></h2></ScrollReveal>{programmes.map((programme) => <ProgrammeFeature key={programme.id} programme={programme} />)}</div></section><CompletedPilot /><ProgrammesCta /></main>;
}
